export const THEMES_OBJECT = [
  { value: "system", option: "System" },
  { value: "light", option: "Light" },
  { value: "dark", option: "Dark" },
  { value: "cupcake", option: "Cupcake" },
  { value: "bumblebee", option: "Bumblebee" },
  { value: "emerald", option: "Emerald" },
  { value: "corporate", option: "Corporate" },
  { value: "halloween", option: "Halloween" },
  { value: "garden", option: "Garden" },
  { value: "lofi", option: "Lofi" },
  { value: "pastel", option: "Pastel" },
  { value: "fantasy", option: "Fantasy" },
  { value: "wireframe", option: "Wireframe" },
  { value: "dracula", option: "Dracula" },
  { value: "cmyk", option: "Cmyk" },
  { value: "autumn", option: "Autumn" },
  { value: "acid", option: "Acid" },
  { value: "lemonade", option: "Lemonade" },
  { value: "night", option: "Night" },
  { value: "winter", option: "Winter" },
];
